Perf: Cache ts offset guesses for quickDT
moment/luxon pull request #1579
Opened 2024-01-22 16:20 UTC by schleyfox

_This is part of a series of PRs based on performance work we have done to
improve a use-case involving parsing/formatting hundreds of thousands of dates
where luxon was the bottleneck._

_This includes the commit from https://github.com/moment/luxon/pull/1574 to establish the benchmark_

Previously we guessed by calling zone.offset(tsNow) on every
construction of a date from date parts. This caches that result instead,
saving a call to offset. The tests verify that this works across DST boundaries when the cache holds an offset for the previous DST state from now.

For processes that live across a DST boundary and mostly handle current date times, this will mean the guess is wrong and we'll have to re-guess. Since we're caching one call to offset, this should be performance neutral to current behavior. Otherwise, we save a call.

Benchmark Comparison (`name | before | after | after/before`):
```
DateTime.local with numbers and zone | 50,913 ±0.18% | 66,168 ±0.25% | 1.3x
```

2024-01-22 20:53 UTC, schleyfox commented
/easycla

2024-01-22 22:15 UTC, icambron requested changes

2024-01-22 22:15 UTC, icambron commented on src/datetime.js
> +      DateTime._zoneOffsetTs = Settings.now();
Should support clearing the cache [here](https://github.com/moment/luxon/blob/3125686af82d9a25c7267a1cf1eb838a3d41144f/src/settings.js#L171)

2024-01-22 22:16 UTC, icambron commented
Looks pretty good. Just requested a few changes

2024-01-22 22:44 UTC, schleyfox commented
Changed, thanks!

2024-03-09 16:49 UTC, icambron commented
@schleyfox if you fix the conflicts, I'll merge this

2024-03-09 17:06 UTC, icambron approved these changes

2024-03-09 21:40 UTC, schleyfox commented
@icambron conflicts fixed. thanks.

2024-03-12 23:52 UTC, merged