update precision pull request
moment/luxon pull request #1670
Opened 2024-12-05 12:42 UTC by dobon

This PR duplicates and updates https://github.com/moment/luxon/pull/748

I've incorporated the feedback from that review and PR, minus renaming "supress[milli]second" which should be in a different PR if the change is made.

2025-04-07 17:04 UTC, diesieben07 requested changes
Should we also support this for calendar units? 
`2024-05` is a valid ISO date, referring to the month of may 2025.

2025-04-07 17:04 UTC, diesieben07 commented on src/datetime.js
> +   * @param {string} [opts.precision='milliseconds'] - specify desired time precision: 'hours', 'minutes', 'seconds' or 'milliseconds'
This should mention
- that it will _truncate_ the output
- How it interacts with `suppressSeconds` and `suppressMilliseconds`

2025-04-11 15:47 UTC, dobon commented
> Should we also support this for calendar units? `2024-05` is a valid ISO date, referring to the month of may 2025.

There was discussion about this in the prior PR, but no conclusion. I've added another commit to enable precision from Year to Millisecond, and it seems good to me. Do the test cases show the function behaving the way you had in mind @diesieben07 ?

Also, I still need to update the method comments to specify truncation behavior and suppressSeconds / suppressMilliseconds behavior (your other comment). I'll include a no-code patch for that in the coming days.

2025-04-13 15:32 UTC, dobon commented on src/datetime.js
> +    return toISODate(this, format === "extended", precisionUnitIndex);
add `if (precisionUnitIndex < 0) throw new InvalidUnitError(precision)` here... except somehow the test is already passing, so investigate why that test is either not working, or else why the system is somehow throwing the correct error anyway.

2025-04-14 01:52 UTC, dobon commented on src/datetime.js
> +    return toISODate(this, format === "extended", precisionUnitIndex);
the error throwing was being handled by the `normalizeUnit` method, so I removed the superfluous error throwing logic.

2025-04-21 09:17 UTC, diesieben07 requested changes

2025-04-21 09:17 UTC, diesieben07 commented on src/datetime.js
> +  switch (precisionUnitIndex) {
I'm not a fan of the code duplication as well as the magic index numbers here.

2025-04-21 12:01 UTC, dobon commented on src/datetime.js
> +  switch (precisionUnitIndex) {
Thanks for the feedback.

Both the loop unraveling(code duplication) and magic index numbers were implemented like that for performance (ie: to minimize comparisons) because toISO can be a hot path.

The loop unravelling was to avoid unnecessary compares on smaller units (eg: if precision is 'days', then don't bother checking if precision is greater than years and months), and the magic index numbers were to facilitate numeric compares instead of string.

That being said, if performance isn't paramount then I agree that the repetitive code reads not-great and I'm happy to re-implement any way you please. As such, I've pushed a commit that passes precision as a string parameter (eliminating the magic numbers), and eliminates the loop unraveling in exchange for a couple more compares. Let me know what you think.

2025-04-21 13:42 UTC, diesieben07 commented on src/datetime.js
> +  switch (precisionUnitIndex) {
I agree that `toISO` should be fast. But we shouldn't make claims about performance without a benchmark :D

2025-04-27 13:20 UTC, merged

2025-04-27 13:20 UTC, diesieben07 commented
Thank you!